language: node_js
node_js:
  - 12

services:
  - docker

before_install:
  - echo "apiKey=$API_KEY" > .env
  - echo "authDomain=$AUTH_DOMAIN" >> .env
  - echo "databaseURL=$DATABASE_URL" >> .env
  - echo "messagingSenderId=$MESSAGING_SENDER_ID" >> .env
  - echo "projectId=$PROJECT_ID" >> .env
  - echo "storageBucket=$STORAGE_BUCKET" >> .env

install:
  - npm i

before_script:
  - npm run lint

script:
  - npm run build

after_success:
  - if [ -n "${TRAVIS_TAG}" ]; then
      docker login -u "$DOCKER_USER" -p "$DOCKER_PW"
      docker build -t poolc/sigahri:production -t poolc/sigahri:latest .;
      docker push poolc/sigahri:latest;
      docker push poolc/sigahri:production;
    fi
