language: node.js

sudo: required

services:
    - docker

before_install:
    - echo "apiKey=$API_KEY" > .env
    - echo "authDomain=$AUTH_DOMAIN" >> .env
    - echo "databaseURL=$DATABASE_URL" >> .env
    - echo "messagingSenderId=$MESSAGING_SENDER_ID" >> .env
    - echo "projectId=$PROJECT_ID" >> .env
    - echo "storageBucket=$STORAGE_BUCKET" >> .env

install:
    - node --version
	- npm --version
    - npm install

script:
    - npm run build

after_success:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t poolc/sigahri .
    - docker push poolc/sigahri
    - if [ -n "${TRAVIS_TAG}"  ]; then
          docker build -t poolc/sigahri:${TRAVIS_TAG} .;
          docker push poolc/sigahri:${TRAVIS_TAG};
      fi
